# Generated by Django 3.2 on 2021-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contacto',
            },
        ),
    ]
