# Generated by Django 3.2 on 2021-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_evento', models.CharField(max_length=50)),
                ('foto1', models.ImageField(upload_to='')),
                ('foto2', models.ImageField(upload_to='')),
                ('foto3', models.ImageField(upload_to='')),
                ('foto4', models.ImageField(upload_to='')),
                ('foto5', models.ImageField(upload_to='')),
                ('foto6', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recuerdo',
                'verbose_name_plural': 'Recuerdo',
            },
        ),
    ]
