# Generated by Django 3.2 on 2021-05-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuerdos',
            name='foto4',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='foto5',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='foto6',
        ),
    ]
