# Generated by Django 3.2 on 2021-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20210522_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuerdos',
            name='contenido',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuerdos',
            name='foto4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuerdos',
            name='foto5',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuerdos',
            name='foto6',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
