# Generated by Django 3.2 on 2021-06-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20210605_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento2',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento3',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento4',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento5',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento6',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento7',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento8',
        ),
        migrations.RemoveField(
            model_name='recuerdos',
            name='titulo_evento9',
        ),
    ]
