# Generated by Django 3.2 on 2021-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='recuerdos')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='recuerdos')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='recuerdos')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recuerdo',
                'verbose_name_plural': 'recurdo',
            },
        ),
    ]
