# Generated by Django 3.2 on 2021-06-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareas_primro',
            new_name='Tareas_primero',
        ),
    ]
