# Generated by Django 3.2 on 2021-06-08 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('opciones', '0002_rename_tareas_primro_tareas_primero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas_primero',
            old_name='titulo',
            new_name='titulo_clase',
        ),
        migrations.AddField(
            model_name='tareas_primero',
            name='correo_profesor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tareas_primero',
            name='nombre_prefesor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas_primero',
            name='secion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
            preserve_default=False,
        ),
    ]
