# Generated by Django 3.2 on 2021-06-08 23:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('opciones', '0003_auto_20210608_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas_tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_clase', models.CharField(max_length=100)),
                ('nombre_prefesor', models.CharField(max_length=50)),
                ('correo_profesor', models.EmailField(blank=True, max_length=254, null=True)),
                ('contenido', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('secion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas_segundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_clase', models.CharField(max_length=100)),
                ('nombre_prefesor', models.CharField(max_length=50)),
                ('correo_profesor', models.EmailField(blank=True, max_length=254, null=True)),
                ('contenido', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('secion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas_quinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_clase', models.CharField(max_length=100)),
                ('nombre_prefesor', models.CharField(max_length=50)),
                ('correo_profesor', models.EmailField(blank=True, max_length=254, null=True)),
                ('contenido', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('secion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas_cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_clase', models.CharField(max_length=100)),
                ('nombre_prefesor', models.CharField(max_length=50)),
                ('correo_profesor', models.EmailField(blank=True, max_length=254, null=True)),
                ('contenido', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('secion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
    ]
