# Generated by Django 3.2 on 2021-06-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0004_tareas_cuarto_tareas_quinto_tareas_segundo_tareas_tercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas_quinto',
            name='apellido_profesor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
