# Generated by Django 3.2 on 2021-06-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0005_tareas_quinto_apellido_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas_cuarto',
            old_name='nombre_prefesor',
            new_name='nombre_profesor',
        ),
        migrations.RenameField(
            model_name='tareas_primero',
            old_name='nombre_prefesor',
            new_name='nombre_profesor',
        ),
        migrations.RenameField(
            model_name='tareas_quinto',
            old_name='apellido_profesor',
            new_name='nombre_profesor',
        ),
        migrations.RenameField(
            model_name='tareas_segundo',
            old_name='nombre_prefesor',
            new_name='nombre_profesor',
        ),
        migrations.RenameField(
            model_name='tareas_tercero',
            old_name='nombre_prefesor',
            new_name='nombre_profesor',
        ),
        migrations.RemoveField(
            model_name='tareas_quinto',
            name='nombre_prefesor',
        ),
    ]
