# Generated by Django 3.2 on 2021-06-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0007_auto_20210608_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas_primero',
            name='telefono',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas_primero',
            name='whatsapp',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
