# Generated by Django 3.2 on 2021-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0009_auto_20210608_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas_quinto',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tareas_quinto',
            name='whatsapp',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
