# Generated by Django 3.2 on 2021-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_primer_estudiante', models.ImageField(blank=True, null=True, upload_to='foto_promedios')),
                ('nombre_primer_estudiante', models.CharField(max_length=50)),
                ('apellido_primer_estudiante', models.CharField(max_length=50)),
                ('seccion_primer_estudiante', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foto_segundo_estudiante', models.ImageField(blank=True, null=True, upload_to='foto_promedios')),
                ('nombre_segundo_estudiante', models.CharField(max_length=50)),
                ('apellido_segundo_estudiante', models.CharField(max_length=50)),
                ('seccion_segundo_estudiante', models.CharField(max_length=50)),
                ('created2', models.DateTimeField(auto_now_add=True)),
                ('foto_tercer_estudiante', models.ImageField(blank=True, null=True, upload_to='foto_promedios')),
                ('nombre_tercer_estudiante', models.CharField(max_length=50)),
                ('apellido_tercer_estudiante', models.CharField(max_length=50)),
                ('seccion_tercer_estudiante', models.CharField(max_length=50)),
                ('created3', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promedio',
                'verbose_name_plural': 'Promedio',
            },
        ),
    ]
