# Generated by Django 3.2 on 2021-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_promedios'),
    ]

    operations = [
        migrations.AddField(
            model_name='promedios',
            name='porsentaje_primer_estudiante',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promedios',
            name='porsentaje_segundo_estudiante',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promedios',
            name='porsentaje_tercer_estudiante',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
