# Generated by Django 3.2 on 2021-06-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_auto_20210528_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncios',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.RenameField(
            model_name='anuncios',
            old_name='descripcion',
            new_name='titulo',
        ),
    ]
