# Generated by Django 3.2 on 2021-06-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_auto_20210604_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promedios',
            name='seccion_primer_estudiante',
        ),
        migrations.RemoveField(
            model_name='promedios',
            name='seccion_segundo_estudiante',
        ),
        migrations.RemoveField(
            model_name='promedios',
            name='seccion_tercer_estudiante',
        ),
    ]
