# Generated by Django 3.2 on 2021-06-05 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_notas_definivas_notas_parciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas_parciales',
            name='user',
        ),
        migrations.AddField(
            model_name='notas_parciales',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
