# Generated by Django 3.2 on 2021-06-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_notas_parciales_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas_parciales',
            old_name='numero',
            new_name='nota',
        ),
        migrations.AddField(
            model_name='notas_parciales',
            name='materia2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas_parciales',
            name='nota2',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
