# Generated by Django 3.2 on 2021-06-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20210605_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_parciales',
            name='nota13',
            field=models.IntegerField(blank=True, default='Por Definir', max_length=2, null=True),
        ),
    ]
