# Generated by Django 3.2 on 2021-06-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_notas_parciales_nota13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_parciales',
            name='nota13',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
