# Generated by Django 3.2 on 2021-06-05 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_alter_notas_parciales_nota13'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas_parciales',
            new_name='Notas_parciales_primer_Lapso',
        ),
    ]
