# Generated by Django 3.2 on 2021-06-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_notas_parciales_notas_parciales_primer_lapso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
