# Generated by Django 3.2 on 2021-06-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20210605_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas_parciales_primer_lapso',
            name='cedula',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
